GET http://localhost:3000/generateImage HTTP/1.1

###

GET http://localhost:3000/generateImage?text=dog%20on%20the%20desk HTTP/1.1

###

GET http://localhost:3000/generateImage HTTP/1.1
content-type: application/json

{
    "text": "cat on the table",
}
